import type { CollectionConfig } from 'payload'

export const SEOMeta: CollectionConfig = {
  slug: 'seo-meta',
  labels: {
    singular: 'SEO 元数据',
    plural: 'SEO 元数据',
  },
  admin: {
    useAsTitle: 'metaTitle',
    defaultColumns: ['pageKey', 'locale', 'metaTitle'],
    description: '管理各页面的 SEO 标题、描述、OG 标签等',
  },
  fields: [
    {
      name: 'pageKey',
      type: 'select',
      required: true,
      label: '页面类型',
      options: [
        { label: 'MP4 下载器', value: 'mp4' },
        { label: 'MP3 转换器', value: 'mp3' },
        { label: '视频下载器', value: 'downloader' },
        { label: '字幕提取器', value: 'transcript' },
        { label: 'M4A 转换器', value: 'm4a' },
      ],
    },
    {
      name: 'locale',
      type: 'select',
      required: true,
      label: '语言',
      options: [
        { label: 'English', value: 'en' },
        { label: '简体中文', value: 'zh-CN' },
        { label: '繁體中文', value: 'zh-TW' },
        { label: '日本語', value: 'ja' },
        { label: '한국어', value: 'ko' },
        { label: 'Español', value: 'es' },
        { label: 'Español (Latam)', value: 'es-419' },
        { label: 'Français', value: 'fr' },
        { label: 'Deutsch', value: 'de' },
        { label: 'Português', value: 'pt' },
        { label: 'Português (BR)', value: 'pt-br' },
        { label: 'Italiano', value: 'it' },
        { label: 'Русский', value: 'ru' },
        { label: 'العربية', value: 'ar' },
        { label: 'हिन्दी', value: 'hi' },
        { label: 'Türkçe', value: 'tr' },
        { label: 'Tiếng Việt', value: 'vi' },
        { label: 'ภาษาไทย', value: 'th' },
        { label: 'Bahasa Indonesia', value: 'id' },
        { label: 'Bahasa Melayu', value: 'ms' },
        { label: 'Filipino', value: 'fil' },
      ],
    },
    {
      name: 'metaTitle',
      type: 'text',
      required: true,
      label: '页面标题（<title> 标签）',
    },
    {
      name: 'metaDescription',
      type: 'textarea',
      required: true,
      label: '页面描述（Meta Description）',
    },
    {
      name: 'ogTitle',
      type: 'text',
      label: 'OG 标题（留空则使用页面标题）',
    },
    {
      name: 'ogDescription',
      type: 'textarea',
      label: 'OG 描述（留空则使用页面描述）',
    },
  ],
}
