name: 手动打包项目

on:
  workflow_dispatch:
    inputs:
      branch:
        description: '选择要打包的分支'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - nuxt
          - transcription
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
      
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      
      - name: 安装依赖
        run: yarn install --frozen-lockfile
      
      - name: generate
        run: yarn generate
      
      - name: pack
        run: |
          cd .output/public
          zip -r ../build-${{ github.event.inputs.branch }}-${{ github.run_number }}.zip .
      
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.event.inputs.branch }}-${{ github.run_number }}
          path: .output/build-${{ github.event.inputs.branch }}-${{ github.run_number }}.zip
          retention-days: 30

      - name: transfer
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }} 
          port: 22
          source: ".output/build-${{ github.event.inputs.branch }}-${{ github.run_number }}.zip"
          target: "/yt"

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }} 
          port: 22
          script: |
            # 安装必要工具
            which unzip || apt-get update && apt-get install -y unzip
            
            # 调试信息
            cd /yt
            echo "当前目录: $(pwd)"
            echo "目录内容:"
            ls -la
            echo "开始解压文件..."
            
            # 解压文件
            unzip -o build-${{ github.event.inputs.branch }}-${{ github.run_number }}.zip -d dist_${{ github.event.inputs.branch }}-${{ github.run_number }}
            
            # 检查解压结果
            echo "解压后的目录内容:"
            ls -la dist_${{ github.event.inputs.branch }}-${{ github.run_number }}
            
            # 替换目录
            echo "替换目录..."
            rm -rf dist1
            mv dist_${{ github.event.inputs.branch }}-${{ github.run_number }} dist1
            echo "部署完成"
            