name: 手动打包项目

on:
  workflow_dispatch:
    inputs:
      branch:
        description: '选择要打包的分支'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - nuxt
          - transcription
      cache:
        description: '是否使用缓存'
        required: true
        default: 'true'
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
      
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      
      - name: 安装依赖
        if: ${{ github.event.inputs.cache == 'true' }}
        run: yarn install --frozen-lockfile
      
      - name: 安装依赖 (无缓存)
        if: ${{ github.event.inputs.cache == 'false' }}
        run: yarn install --frozen-lockfile --force
      
      - name: generate
        run: yarn generate
      
      - name: pack
        run: |
          cd .output/public
          zip -r ../build-${{ github.event.inputs.branch }}-${{ github.run_number }}.zip .
      
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.event.inputs.branch }}-${{ github.run_number }}
          path: .output/build-${{ github.event.inputs.branch }}-${{ github.run_number }}.zip
          retention-days: 30

      - name: transfer
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: ".output/build-${{ github.event.inputs.branch }}-${{ github.run_number }}.zip"
          target: "/yt"

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /yt
            unzip build-${{ github.event.inputs.branch }}-${{ github.run_number }}.zip -d dist_${{ github.event.inputs.branch }}-${{ github.run_number }}
            rm -rf dist1
            mv dist_${{ github.event.inputs.branch }}-${{ github.run_number }} dist1
            