name: 手动打包项目

on:
  workflow_dispatch:
    inputs:
      branch:
        description: '选择要打包的分支'
        required: true
        default: 'transcription'
        type: choice
        options:
          - nuxt
          - transcription
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Generate
        run: yarn generate
      
      - name: Pack
        run: |
          cd .output/public
          zip -r ../dist-${{ github.event.inputs.branch }}-${{ github.run_number }}-${{ steps.date.outputs.date }}.zip .
          # 将构建产物复制到工作目录根目录
          cp ../dist-${{ github.event.inputs.branch }}-${{ github.run_number }}-${{ steps.date.outputs.date }}.zip ../../
      
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ github.event.inputs.branch }}-${{ github.run_number }}-${{ steps.date.outputs.date }}
          path: dist-${{ github.event.inputs.branch }}-${{ github.run_number }}-${{ steps.date.outputs.date }}.zip
          retention-days: 30

      - name: transfer
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }} 
          port: 22
          source: "dist-${{ github.event.inputs.branch }}-${{ github.run_number }}-${{ steps.date.outputs.date }}.zip"
          target: "/yt"

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }} 
          port: 22
          script: |
            # 安装必要工具
            which unzip || apt-get update && apt-get install -y unzip
            
            # 调试信息
            cd /yt
            echo "当前目录: $(pwd)"
            echo "目录内容:"
            ls -la
            echo "开始解压文件..."
            
            # 解压文件
            unzip -o dist-${{ github.event.inputs.branch }}-${{ github.run_number }}-${{ steps.date.outputs.date }}.zip -d dist-${{ github.event.inputs.branch }}-${{ github.run_number }}-${{ steps.date.outputs.date }}
            
            # 检查解压结果
            echo "解压后的目录内容:"
            ls -la dist-${{ github.event.inputs.branch }}-${{ github.run_number }}-${{ steps.date.outputs.date }}
            
            # 替换目录
            echo "替换目录..."
            rm -rf dist
            cp -r dist-${{ github.event.inputs.branch }}-${{ github.run_number }}-${{ steps.date.outputs.date }} dist
            echo "部署完成"
            